[package]
authors = ["dnaq"]
description = "Fast cryptographic library for Rust (bindings to libsodium)"
documentation = "https://dnaq.github.io/sodiumoxide"
keywords = ["crypto", "NaCl", "libsodium"]
license = "MIT"
name = "sodiumoxide"
readme = "README.md"
repository = "https://github.com/dnaq/sodiumoxide"
version = "0.0.9"

[dependencies]
libc = "0.2.1"
libsodium-sys = "0.0.9"
rustc-serialize = { version = "0.3.16", optional = true }

[dev-dependencies]
rustc-serialize = "0.3.16"

[features]
benchmarks = []
default = ["rustc-serialize"]
